### ISSUE TITLE
How to Use Proxy to connect to MS

### ISSUE THREAD

**Issue by SaschaBrechmannVHV** [NETWAYS/check_microsoft365#20]
My Monitoring-System do not have direct internet access. I need to use the company proxy to get internet access.
How could i use this nice plugin with Proxy ? Like i do it with the check_http plugin ?
Regrads, Sascha

**Comment by martialblog** [comment]
Hi, we currently don't have a flag to specify where the API endpoint is... mainly cause we use the SDK. But we can evaluate if that's possible.

**Comment by martialblog** [comment]
Hi, we're currently working on a refactor that would allow for this feature.

**Comment by martialblog** [comment]
One issue with this is, that we have two URLs to worry about. 

The API is at https://graph.microsoft.com/ but we get our Bearer token from  https://login.microsoftonline.com

**Comment by martialblog** [comment]
@SaschaBrechmannVHV just our of curiosity, have you considered using a DNS entry that points to the Proxy as a workaround?

**Comment by martialblog** [comment]
The Azure SDK has some Microsoft endpoints hardcoded (i.e. "https://login.microsoftonline.com/common") which makes it tricky to override with CLI Flags. For now I don't think we can support this feature, but a workaround could to use DNS to change the address of login.microsoftonline.com

**Comment by martialblog** [comment]
Unfortunately, Since the  Azure SDK has these endpoints hardcoded it is currently not feasible for use to provide this feature.
