### ISSUE TITLE
Feature request: Display the message text in the plugin output

### ISSUE THREAD

**Issue by aheinhold** [NETWAYS/check_microsoft365#4]
Hi @pdorschner ,

can you please add to the plugin that the "message text" is also displayed in the plugin output?

Regards,
Alex

**Comment by pdorschner** [comment]
Hi @aheinhold,

could you specify what you mean with `message text`? Maybe you can give an example plugin output how I should look like.

Cheers,
Philipp

**Comment by aheinhold** [comment]
I received this example from our M365 administrators. Details about the incident are shown in the message text.
For example, there was a recent outage that only affected users in China.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/45874736/165903712-04018182-635c-40d6-a83e-c69214e06847.png)
